table 'Sales Order'

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Sales Order Line

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["IsHidden"]

	hierarchy 'Sales Orders'

		level 'Sales Order Line'
			column: 'Sales Order Line'

	partition 'Sales Order' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(HttpSource & "Sales Order.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesOrderLineKey", Int64.Type}, {"Sales Order", type text}, {"Sales Order Line", type text}, {"Channel", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

